Repository itcen-project-2team/sketch-quiz-server, pull requests merged in 2025-06, with the labels that each got.

#17 [문서] API.md 작성
  API.md
Labels: documentation

#21 [게임] 게임 시작 ~ 게임 종료까지의 기능 구현
  src/main/java/com/itcen/whiteboardserver/chatting/controller/ChattingController.java
  src/main/java/com/itcen/whiteboardserver/chatting/dto/ChattingRequest.java
  src/main/java/com/itcen/whiteboardserver/chatting/service/ChattingService.java
  src/main/java/com/itcen/whiteboardserver/chatting/service/ChattingServiceImpl.java
  src/main/java/com/itcen/whiteboardserver/game/dto/response/GameParticipantResponse.java
  src/main/java/com/itcen/whiteboardserver/game/dto/response/GameStartedResponse.java
  src/main/java/com/itcen/whiteboardserver/game/dto/response/RoomInfoResponse.java
  src/main/java/com/itcen/whiteboardserver/game/dto/response/RoomParticipantResponse.java
  src/main/java/com/itcen/whiteboardserver/game/entity/Game.java
  src/main/java/com/itcen/whiteboardserver/game/entity/GameParticipation.java
  src/main/java/com/itcen/whiteboardserver/game/entity/Turn.java
  src/main/java/com/itcen/whiteboardserver/game/event/WebSocketEventListener.java
  src/main/java/com/itcen/whiteboardserver/game/mapper/GameMapper.java
  src/main/java/com/itcen/whiteboardserver/game/repository/GameParticipationRepository.java
  src/main/java/com/itcen/whiteboardserver/game/service/GameService.java
  src/main/java/com/itcen/whiteboardserver/game/service/QuizService.java
  src/main/java/com/itcen/whiteboardserver/game/service/RoomService.java
  src/main/java/com/itcen/whiteboardserver/game/session/GameSession.java
  src/main/java/com/itcen/whiteboardserver/game/session/state/GameState.java
  src/main/java/com/itcen/whiteboardserver/game/session/state/GameStatus.java
  src/main/java/com/itcen/whiteboardserver/turn/dto/response/TurnResponse.java
  src/main/java/com/itcen/whiteboardserver/turn/dto/response/TurnResponseType.java
  src/main/java/com/itcen/whiteboardserver/turn/dto/response/data/CorrectData.java
  src/main/java/com/itcen/whiteboardserver/turn/dto/response/data/DrawerData.java
  src/main/java/com/itcen/whiteboardserver/turn/dto/response/data/MemberScore.java
  src/main/java/com/itcen/whiteboardserver/turn/dto/response/data/TurnData.java
  src/main/java/com/itcen/whiteboardserver/turn/dto/response/data/TurnQuitData.java
  src/main/java/com/itcen/whiteboardserver/turn/entitiy/Correct.java
  src/main/java/com/itcen/whiteboardserver/turn/entitiy/Turn.java
  src/main/java/com/itcen/whiteboardserver/turn/mapper/TurnMapper.java
  src/main/java/com/itcen/whiteboardserver/turn/repository/CorrectRepository.java
  src/main/java/com/itcen/whiteboardserver/turn/repository/TurnRepository.java
  src/main/java/com/itcen/whiteboardserver/turn/service/TurnService.java
  src/main/java/com/itcen/whiteboardserver/turn/service/TurnServiceImpl.java
  src/main/resources/static/websocket-test.html
Labels: Feature

#54 [게임] 게임 동시성 제어 로직
  src/main/java/com/itcen/whiteboardserver/game/entity/Game.java
  src/main/java/com/itcen/whiteboardserver/game/repository/RoomRepository.java
  src/main/java/com/itcen/whiteboardserver/game/session/GameSession.java
  src/main/java/com/itcen/whiteboardserver/game/session/state/GameState.java
  src/main/java/com/itcen/whiteboardserver/turn/service/TurnServiceImpl.java
Labels: enhancement
